//
//  CitiesDetailRouter.swift
//  WeatherApp_test
//
//  Created by Миша Москвичев on 06.10.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CitiesDetailRoutingLogic {

}

protocol CitiesDetailDataPassing {
  var dataStore: CitiesDetailDataStore? { get }
}

class CitiesDetailRouter: CitiesDetailDataPassing {
    
    weak var dataStore: CitiesDetailDataStore?
  
}

extension CitiesDetailRouter: CitiesDetailRoutingLogic {
    
}
