//
//  CitiesInteractor.swift
//  WeatherApp_test
//
//  Created by Миша Москвичев on 06.10.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CitiesBusinessLogic {
  func fetchCities()
}

protocol CitiesDataStore
{
  //var name: String { get set }
}

class CitiesInteractor {
    
    //MARK: - External vars
  var presenter: CitiesPresentationLogic?
//  var worker: CitiesWorker?
    
}

//MARK: - Business logic

extension CitiesInteractor: CitiesBusinessLogic {
    func fetchCities() {
        presenter?.presentData()
    }
    
    
}

