//
//  CitiesPresenter.swift
//  WeatherApp_test
//
//  Created by Миша Москвичев on 06.10.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CitiesPresentationLogic {
  func presentData()
}

class CitiesPresenter {
    
    //MARK: - External vars
    weak var viewController: CitiesDisplayLogic?
}

//MARK: - Presentation logic

extension CitiesPresenter: CitiesPresentationLogic {
    func presentData() {
        
    }
    
}
  
  // MARK: Do something
  
//  func presentSomething(response: Cities.Something.Response) {
//    let viewModel = Cities.Something.ViewModel()
//    viewController?.displaySomething(viewModel: viewModel)
//  }
    
