//
//  CitiesPresenter.swift
//  WeatherApp_test
//
//  Created by Миша Москвичев on 06.10.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CitiesPresentationLogic {
    func present(data: [WeatherBackendModel])
}

class CitiesPresenter {
    
    //MARK: - External vars
    weak var viewController: CitiesDisplayLogic?
}

//MARK: - Presentation logic

extension CitiesPresenter: CitiesPresentationLogic {
    
    func present(data: [WeatherBackendModel]) {
        let viewModel = data.map { model -> WeatherCellModel in
            let cellModel = WeatherCellModel(cityId: Int(model.cityId) ?? 0, cityName: model.name, temperature: model.text)
            
            return cellModel
        }
        viewController?.display(data: viewModel)
    }
}
  
  // MARK: Do something
  
//  func presentSomething(response: Cities.Something.Response) {
//    let viewModel = Cities.Something.ViewModel()
//    viewController?.displaySomething(viewModel: viewModel)
//  }
    
